name: tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
        - os: ubuntu-latest
        - os: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'install bashunit'
      run: |
        ./install_bashunit.sh

    - name: Run tests
      run: |
        ./tests.sh
